name: Deploy one-click apps

on:
  workflow_dispatch:

jobs:
  tests:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    timeout-minutes: 360
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble
      options: --user 1001

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Run end-to-end tests
        run: pnpm e2e
        env:
          CI: 'true'
          BASE_URL: ${{ vars.E2E_BASE_URL }}
          WEBSITE_BASE_URL: ${{ vars.E2E_WEBSITE_BASE_URL }}
          USER_TOKEN: ${{ secrets.E2E_USER_TOKEN }}
          USER_EMAIL: ${{ vars.E2E_USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.E2E_USER_PASSWORD }}
          USER_GITHUB_PASSWORD: ${{ secrets.E2E_USER_GITHUB_PASSWORD }}
          USER_GITHUB_TOTP_KEY: ${{ secrets.E2E_USER_GITHUB_TOTP_KEY }}
          ONE_CLICK_APP: all
